package com.example.user;
import java.util.Date;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class User {
	//Declare all variables used for the entity
	//User ID is the primary key and it is automatically generated by the DB
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long userId;
	
	//User attributes
	private String firstName, lastName, username, email, mobileNo, address, postalCode, password, userStatus;
	
	//Date attributes
	private Date createdDate, suspendDate, unsuspendDate, terminateDate, unterminateDate, inactiveDate;
	
	//No argument constructor
	public User() {}
	
	//Constructor with all fields
	public User(Long userId, String firstName, String lastName, String username, String email, String mobileNo, String address, String postalCode, String password, String userStatus, Date createdDate, 
	Date suspendDate, Date unsuspendDate, Date terminateDate, Date unterminateDate, Date inactiveDate) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.email = email;
		this.mobileNo = mobileNo;
		this.address = address;
		this.postalCode = postalCode;
		this.password = password;
		this.userStatus = userStatus;
		this.createdDate = createdDate;
		this.suspendDate = suspendDate;
		this.unsuspendDate = unsuspendDate;
		this.terminateDate = terminateDate;
		this.unterminateDate = unterminateDate;
		this.inactiveDate = inactiveDate;
	}
	
	//Getters
	public Long getUserId() {
		return userId;
	}
	
	public String getFirstName() {
		return firstName;
	}
	
	public String getLastName() {
		return lastName;
	}
	
	public String getUsername() {
		return username;
	}
	
	public String getEmail() {
		return email;
	}
	
	public String getMobileNo() {
		return mobileNo;
	}
	
	public String getAddress () {
		return address;
	}
	
	public String getPostalCode () {
		return postalCode;
	}
	
	public String getPassword () {
		return password;
	}
	
	public String getUserStatus () {
		return userStatus;
	}
	
	public Date getCreatedDate () {
		return createdDate;
	}
	
	public Date getSuspendDate () {
		return suspendDate;
	}
	
	public Date getUnsuspendDate () {
		return unsuspendDate;
	}
	
	public Date getTerminateDate () {
		return terminateDate;
	}
	
	public Date getUnterminateDate () {
		return unterminateDate;
	}
	
	public Date getInactiveDate () {
		return inactiveDate;
	}
	
	//Setters
	public Long setUserId(Long userId) {
		return userId;
	}
	
	public String setFirstName(String firstName) {
		return firstName;
	}
	
	public String setLastName(String lastName) {
		return lastName;
	}
	
	public String setUsername(String username) {
		return username;
	}
	
	public String setEmail(String email) {
		return email;
	}
	
	public String setMobileNo(String mobileNo) {
		return mobileNo;
	}
	
	public String setAddress (String address) {
		return address;
	}
	
	public String setPostalCode (String postalCode) {
		return postalCode;
	}
	
	public String setPassword (String password) {
		return password;
	}
	
	public String setUserStatus (String userStatus) {
		return userStatus;
	}
	
	public Date setCreatedDate (Date createdDate) {
		return createdDate;
	}
	
	public Date setSuspendDate (Date suspendDate) {
		return suspendDate;
	}
	
	public Date setUnsuspendDate (Date unsuspendDate) {
		return unsuspendDate;
	}
	
	public Date setTerminateDate (Date terminateDate) {
		return terminateDate;
	}
	
	public Date setUnterminateDate (Date terminateDate) {
		return unterminateDate;
	}
	
	public Date setInactiveDate (Date inactiveDate) {
		return inactiveDate;
	}
}