package com.example.user;
import java.util.Date;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class User {
	//Declare all variables used for the entity
	//User ID is the primary key and it is automatically generated by the DB
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long userId;
	
	//User attributes
	private String firstName, lastName, username, email, mobileNo, address, postalCode, password, userStatus;
	
	//Date attributes
	private Date createdDate, suspendDate, unsuspendDate, terminateDate, unterminateDate, inactiveDate;
	
	//No argument constructor
	public User() {}
	
	//Constructor with all fields
	public User(Long userId, String firstName, String lastName, String username, String email, String mobileNo, String address, String postalCode, String password, String userStatus, Date createdDate, 
	Date suspendDate, Date unsuspendDate, Date terminateDate, Date unterminateDate, Date inactiveDate) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.email = email;
		this.mobileNo = mobileNo;
		this.address = address;
		this.postalCode = postalCode;
		this.password = password;
		this.userStatus = userStatus;
		this.createdDate = createdDate;
		this.suspendDate = suspendDate;
		this.unsuspendDate = unsuspendDate;
		this.terminateDate = terminateDate;
		this.unterminateDate = unterminateDate;
		this.inactiveDate = inactiveDate;
	}
	
	//Getters
	public Long getUserId() {
		return userId;
	}
	
	public String getFirstName() {
		return firstName;
	}
	
	public String getLastName() {
		return lastName;
	}
	
	public String getUsername() {
		return username;
	}
	
	public String getEmail() {
		return email;
	}
	
	public String getMobileNo() {
		return mobileNo;
	}
	
	public String getAddress () {
		return address;
	}
	
	public String getPostalCode () {
		return postalCode;
	}
	
	public String getPassword () {
		return password;
	}
	
	public String getUserStatus () {
		return userStatus;
	}
	
	public Date getCreatedDate () {
		return createdDate;
	}
	
	public Date getSuspendDate () {
		return suspendDate;
	}
	
	public Date getUnsuspendDate () {
		return unsuspendDate;
	}
	
	public Date getTerminateDate () {
		return terminateDate;
	}
	
	public Date getUnterminateDate () {
		return unterminateDate;
	}
	
	public Date getInactiveDate () {
		return inactiveDate;
	}
	
	//Setters
		public void setUserId(Long userId) {
			this.userId = userId;
		}

		public void setFirstName(String firstName) {
			this.firstName = firstName;
		}

		public void setLastName(String lastName) {
			this.lastName = lastName;
		}

		public void setUsername(String username) {
			this.username = username;
		}

		public void setEmail(String email) {
			this.email = email;
		}

		public void setMobileNo(String mobileNo) {
			this.mobileNo = mobileNo;
		}

		public void setAddress (String address) {
			this.address = address;
		}

		public void setPostalCode (String postalCode) {
			this.postalCode = postalCode;
		}

		public void setPassword (String password) {
			this.password = password;
		}

		public void setUserStatus (String userStatus) {
			this.userStatus = userStatus;
		}

		public void setCreatedDate (Date createdDate) {
			this.createdDate = createdDate;
		}

		public void setSuspendDate (Date suspendDate) {
			this.suspendDate = suspendDate;
		}

		public void setUnsuspendDate (Date unsuspendDate) {
			this.unsuspendDate = unsuspendDate;
		}
		
		public void setTerminateDate (Date terminateDate) {
			this.terminateDate = terminateDate;
		}
		
		public void setUnterminateDate (Date unterminateDate) {
			this.unterminateDate = unterminateDate;
		}

		public void setInactiveDate (Date inactiveDate) {
			this.inactiveDate = inactiveDate;
		}
}