package com.example.user.Entity;
import java.util.Date;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

@Entity
public class User {
	/*
	 * Declare all variables used for the entity
	 * User ID: PK and is automatically generated by DB
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long userId;

	//User attributes
	private String firstName, lastName, username, email, mobileNo, address, postalCode, password, userStatus, role;

	//Date attributes
	private Date createdDate, suspensionDate, unsuspensionDate, terminationDate, unterminationDate, inactiveDate;

	//No argument constructor
	public User() {}

	//Constructor with all fields
	public User(Long userId, String firstName, String lastName, String username, String email, String mobileNo, String address, String postalCode, String password, String role, String userStatus, Date createdDate, 
	Date suspensionDate, Date unsuspensionDate, Date terminationDate, Date unterminationDate, Date inactiveDate) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.email = email;
		this.mobileNo = mobileNo;
		this.address = address;
		this.postalCode = postalCode;
		this.password = password;
		this.role = role;
		this.userStatus = userStatus;
		this.createdDate = createdDate;
		this.suspensionDate = suspensionDate;
		this.unsuspensionDate = unsuspensionDate;
		this.terminationDate = terminationDate;
		this.unterminationDate = unterminationDate;
		this.inactiveDate = inactiveDate;
	}

	//Getters
	public Long getUserId() {
		return userId;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public String getUsername() {
		return username;
	}

	public String getEmail() {
		return email;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public String getAddress () {
		return address;
	}

	public String getPostalCode () {
		return postalCode;
	}

	public String getPassword () {
		return password;
	}
	
	public String getRole () {
		return role;
	}

	public String getUserStatus () {
		return userStatus;
	}

	public Date getCreatedDate () {
		return createdDate;
	}

	public Date getSuspensionDate () {
		return suspensionDate;
	}

	public Date getUnsuspensionDate () {
		return unsuspensionDate;
	}

	public Date getTerminationDate () {
		return terminationDate;
	}

	public Date getUnterminationDate () {
		return unterminationDate;
	}

	public Date getInactiveDate () {
		return inactiveDate;
	}

	//Setters
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public void setAddress (String address) {
		this.address = address;
	}

	public void setPostalCode (String postalCode) {
		this.postalCode = postalCode;
	}

	public void setPassword (String password) {
		BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
		this.password = passwordEncoder.encode(password);	//Store hashed password into DB
	}
	
	public boolean checkPassword(String password) {
		BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
		return passwordEncoder.matches(password, this.password);	//Check raw passsword against hashed password
	}
	
	public void setRole(String role) {
		this.role = role;
	}

	public void setUserStatus (String userStatus) {
		this.userStatus = userStatus;
	}

	public void setCreatedDate (Date createdDate) {
		this.createdDate = createdDate;
	}

	public void setSuspensionDate (Date suspensionDate) {
		this.suspensionDate = suspensionDate;
	}

	public void setUnsuspensionDate (Date unsuspensionDate) {
		this.unsuspensionDate = unsuspensionDate;
	}

	public void setTerminationDate (Date terminationDate) {
		this.terminationDate = terminationDate;
	}

	public void setUnterminationDate (Date unterminationDate) {
		this.unterminationDate = unterminationDate;
	}

	public void setInactiveDate (Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}
}